### PR TITLE
Search config file in `XDG_CONFIG_HOME` even on Windows

### LINKED ISSUE #71: Search config file under `$XDG_CONFIG_HOME` even on Windows
I know the XDG spec is normally a Linux thing, but it works quite well for me to configure a number of cross-platform tools I use, and that respects `XDG_CONFIG_HOME` everywhere when it is set.

I use it to relocate a number of config files to a known path of mine, a git repo where I want, and avoids having config files in the obscure standards windows locations like APPDATA.

The current code uses:
https://github.com/tridactyl/native_messenger/blob/6e0d2cd3bc7dab02e8e87aaaa60b52c20131db42/src/native_main.nim#L88-L102
Using the same set of candidate files on both wouldn't work either because Nim's `getConfigPath` always returns `APPDATA` on windows:
https://github.com/nim-lang/Nim/blob/cd84cd45ea5bc1de67dd28dab906ad6c16e7b092/lib/std/private/osappdirs.nim#L72

So we'll need to make a special case here.

### PR DESCRIPTION
**Pull request by bew**
Also adds the Windows' standard directory in $APPDATA

NOTE: The code was not tested, and was made by looking at the code around and doing something similar.

Closes #71

### CODE REVIEW

**Comment by bew** [comment]
I tested the binary from github action by replacing the installed binary by that one.

Works well for me 👍

**Comment by bew** [comment]
Cool thanks! 👌

So will new users / me in some time get this directly with normal install? or do you need to do a release?
(I basically want to know what to write in my own config README regarding this new behavior)

**Comment by bovine3dom** [comment]
I need to do all the steps in #4 and then do a beta/stable release of Tridactyl

In theory the native messenger should get updated automatically but in practice it never happens, you you'll need to rerun `:nativeinstall`

**Comment by bew** [comment]
Thank you for the release 👍

**Pull request merged**
