### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by SolitudeSF**
make code slightly more idiomatic. remove dependency on `struct`. demote `Option[string]` to `string` for fields where empty string is functionally equivalent to `none`. manually generate JsonNode to reduce size of json payload.

look at the `refactoring` commit to ignore indentation changes. can split it up later if needed.

### CODE REVIEW

**Comment by bovine3dom** [comment]
Hi, thanks a lot for this!

This mostly looks great but I'm not 100% keen on `toJson` as it will make adding new fields a little bit more annoying. As a rule of thumb I value programmer time much higher than user time : )

I'll try and review and get this merged soon as it looks like a "grasp the nettle" PR where it'll get stale very quickly.

**Comment by SolitudeSF** [comment]
toJson reduces payload size and simplifies other code, since we dont have to rely on Option just to generate `null` fields.

**Comment by bovine3dom** [comment]
I think ideally it would throw a compile-time error if there were any properties in MessageResp that it didn't handle. I'm concerned that someone will add a property and then spend a long time trying to work out why their code isn't working

**Comment by SolitudeSF** [comment]
i made so it raises compile time error if a field isnt handled in `toJson`

**Pull request merged**
